package.path = table.concat({
  "./?.lua",
  "./?/init.lua",
  package.path,
}, ";")

local tests = {
  (require("tests.integration.dummy_loopback")),
  (require("tests.integration.dcutr_auto_policy")),
  (require("tests.integration.dcutr_handshake_e2e")),
  (require("tests.integration.dcutr_unilateral_fallback")),
  (require("tests.integration.dcutr_relay_grace_close")),
  (require("tests.integration.dcutr_retry_events")),
  (require("tests.integration.identify_tcp")),
  (require("tests.integration.host_luv_runtime_identify_event")),
  (require("tests.integration.host_luv_native_coroutine_resume")),
  (require("tests.integration.host_luv_scheduler_pump_noise_ping_subprocess")),
  (require("tests.integration.host_luv_scheduler_pump_noise_ping_ipv6_subprocess")),
  (require("tests.integration.host_luv_scheduler_pump_ping_subprocess")),
  (require("tests.integration.host_luv_scheduler_identify_autorelay_dht_pressure")),
  (require("tests.integration.host_luv_scheduler_pump_stream_error_kinds_subprocess")),
  (require("tests.integration.kad_dht_provide_find_providers")),
  (require("tests.integration.kad_dht_put_find_value")),
  (require("tests.integration.host_oversized_mss")),
  (require("tests.integration.mss_tcp_framing")),
  (require("tests.integration.ping_tcp")),
  (require("tests.integration.plaintext_tcp")),
  (require("tests.integration.tcp_loopback")),
  (require("tests.integration.tcp_luv_loopback")),
  (require("tests.integration.yamux_tcp")),
  (require("tests.unit.loopback_errors")),
  (require("tests.unit.multiaddr")),
  (require("tests.unit.multiaddr_bytes")),
  (require("tests.unit.multiaddr_vectors")),
  (require("tests.unit.multiaddr_go_deltas")),
  (require("tests.unit.tcp_multiaddr")),
  (require("tests.unit.tcp_luv")),
  (require("tests.unit.address_manager")),
  (require("tests.unit.bootstrap")),
  (require("tests.unit.discovery")),
  (require("tests.unit.datastore")),
  (require("tests.unit.datastore_sqlite")),
  (require("tests.unit.log")),
  (require("tests.unit.key_pb")),
  (require("tests.unit.host")),
  (require("tests.unit.host_advertise")),
  (require("tests.unit.host_bind_rollback")),
  (require("tests.unit.host_connections")),
  (require("tests.unit.host_events")),
  (require("tests.unit.host_identify_on_connect")),
  (require("tests.unit.host_peerstore_datastore")),
  (require("tests.unit.host_services_identify")),
  (require("tests.unit.host_services_ping")),
  (require("tests.unit.host_protocols")),
  (require("tests.unit.host_relay_dial")),
  (require("tests.unit.host_resource_manager")),
  (require("tests.unit.host_service_manager")),
  (require("tests.unit.host_tasks")),
  (require("tests.unit.host_nonfatal_errors")),
  (require("tests.unit.host_runtime_luv")),
  (require("tests.unit.autonat_v2")),
  (require("tests.unit.autonat_client")),
  (require("tests.unit.dcutr")),
  (require("tests.unit.upnp")),
  (require("tests.unit.identify")),
  (require("tests.unit.circuit_relay_v2")),
  (require("tests.unit.relay_client")),
  (require("tests.unit.relay_autorelay")),
  (require("tests.unit.resource_manager")),
  (require("tests.unit.kad_dht")),
  (require("tests.unit.kad_dht_bootstrap")),
  (require("tests.unit.kad_dht_dnsaddr")),
  (require("tests.unit.kad_dht_protocol")),
  (require("tests.unit.kad_dht_providers")),
  (require("tests.unit.kad_dht_records")),
  (require("tests.unit.kad_dht_refresh")),
  (require("tests.unit.kad_dht_maintenance")),
  (require("tests.unit.kbucket")),
  (require("tests.unit.mss")),
  (require("tests.unit.network_connection")),
  (require("tests.unit.noise")),
  (require("tests.unit.noise_ecdsa")),
  (require("tests.unit.noise_rsa")),
  (require("tests.unit.noise_secp256k1")),
  (require("tests.unit.noise_xx")),
  (require("tests.unit.peerstore")),
  (require("tests.unit.peerstore_codec")),
  (require("tests.unit.peerstore_datastore")),
  (require("tests.unit.signed_envelope")),
  (require("tests.unit.rockspec")),
  (require("tests.unit.peer_record")),
  (require("tests.unit.perf")),
  (require("tests.unit.ping")),
  (require("tests.unit.plaintext")),
  (require("tests.unit.upgrader")),
  (require("tests.unit.upgrader_noise")),
  (require("tests.unit.yamux")),
  (require("tests.unit.ed25519")),
  (require("tests.unit.peerid")),
  (require("tests.unit.peerid_ecdsa")),
  (require("tests.unit.spec_vectors_ecdsa")),
  (require("tests.unit.spec_vectors_ed25519")),
  (require("tests.unit.spec_vectors_rsa")),
  (require("tests.unit.spec_vectors_secp256k1")),
  (require("tests.unit.multiformats")),
}

local failed = 0

for _, t in ipairs(tests) do
  local ok, err = t.run()
  if ok then
    io.stdout:write(string.format("[PASS] %s\n", t.name))
  else
    failed = failed + 1
    io.stderr:write(string.format("[FAIL] %s: %s\n", t.name, tostring(err)))
  end
end

if failed > 0 then
  io.stderr:write(string.format("%d test(s) failed\n", failed))
  os.exit(1)
end

io.stdout:write(string.format("%d test(s) passed\n", #tests))
